definitions:
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      description: ping 测试处理函数
      responses:
        "200":
          description: 请求错误
          schema:
            $ref: '#/definitions/response.Response'
      summary: ping
      tags:
      - Base
swagger: "2.0"
