service:
  # 服务名称
  name: change
  # 服务别名
  nickname: Chang'e
  # 监听地址
  listen: 0.0.0.0
  # 监控端口
  port: 10000
  # 运行模式，支持 debug 和 release
  mode: debug
  # 路由前缀
  api-prefix: /api/v1

mysql:
  # 连接地址
  host: 127.0.0.1
  # 连接端口
  port: 3306
  # 数据库
  database: change
  # 用户
  username: root
  # 密码
  password: 123456
  # 字符编码
  charset: utf8mb4
  # 排序规则
  collation: utf8mb4_general_ci
  # 超时时间，ms
  timeout: 10000
  # 连接串
  ext-query: parseTime=True&loc=Local
  # 最大空闲连接数
  max-idle-conns: 10
  # 最大打开连接数
  max-open-conns: 100
  # 最大链接复用时间，分钟
  max-idle-time: 60
  # 慢查询耗时，毫秒
  slow-threshold: 100

redis:
  # 连接地址
  host: 127.0.0.1
  # 连接端口
  port: 6379
  # 数据库
  db: 1
  # 密码，如果没密码则不设置
  password: ""

# 日志配置
log:
  # 是否访问日志写入到日志文件
  enable: true
  # 日志文件存放目录
  path: logs
  # 日志等级，参考 zapcore.Level（-1<=level<=5，-1 / DEBUG）
  level: -1
  # 颜色输出
  color: false
  # 日志大小，单位 m
  max-size: 100
  # 保留个数
  max-backups: 10
  # 保留天数
  max-age: 7
  # 是否压缩
  compress: true
  # 是否将 SQL 日志写入到日志文件
  sql-log-enable: true
  # SQL 日志级别，(1-4，Info，Warn，Error, Silent)，4 不输出日志，生产建议 2
  sql-log-level: 1

jwt:
  # JWT 标识
  realm: change
  # 签名的秘钥
  key: change-key
  # Token 超时时间，单位秒，默认一天
  timeout: 86400

login:
  # 允许错误密码次数，设置为 0 则不启用
  allow-wrong-times: 10
  # 允许错误的最大次数，达到上限就锁定用户，需要大于 allow-wrong-times
  allow-max-wrong-times: 15
  # 登录失败次数达到上限后，需要等待时间，秒
  max-wrong-wait-time: 30
  # 是否允许多个设备同时在线
  allow-multiple-devices: false

